In [1]:
# Import the libraries

import numpy as np

In [2]:
# Consider the list a, which contains three nested lists each of equal size.

a = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [3]:
A = np.array(a)
A

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [4]:
# Show the numpy array dimensions

A.ndim

2

In [5]:
# Show the numpy array size

A.size

9

In [6]:
# Access the element on the first row and first column

A[0][0]

11

In [7]:
# Access the element on the first row and first and second columns

A[0][0:2]

array([11, 12])

In [8]:
# Access the element on the first and second rows and third column

A[0:2, 2]

array([13, 23])

In [9]:
# Create a numpy array X

X = np.array([[1, 0], [0, 1]]) 
print(X)

# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
print(Y)

[[1 0]
 [0 1]]
[[2 1]
 [1 2]]


In [10]:
# Add X and Y

Z = X + Y
Z

array([[3, 1],
       [1, 3]])

In [11]:
# Create a numpy array Y

Y = np.array([[2, 1], [1, 2]]) 
print(Y)

# Multiply Y with 2

Z = 2 * Y
print(Z)

[[2 1]
 [1 2]]
[[4 2]
 [2 4]]
